print("Welcome to Python Programming")
print("Preparation for Parallel Programming and Machine Learning")
print("BS Computer Science 4")
print("BS Computer Science 4")
print("CCSICT Echague Campus")